from __future__ import annotations

from enum import StrEnum
from typing import Any


class ArtifactErrorCode(StrEnum):
    ARTIFACT_NOT_FOUND = "ARTIFACT_NOT_FOUND"
    ARTIFACT_KIND_UNSUPPORTED = "ARTIFACT_KIND_UNSUPPORTED"
    ARTIFACT_SCHEMA_VERSION_UNSUPPORTED = "ARTIFACT_SCHEMA_VERSION_UNSUPPORTED"
    ARTIFACT_SCHEMA_INVALID = "ARTIFACT_SCHEMA_INVALID"
    ARTIFACT_CONTENT_TOO_LARGE = "ARTIFACT_CONTENT_TOO_LARGE"
    ARTIFACT_REVISION_CONFLICT = "ARTIFACT_REVISION_CONFLICT"
    IDEMPOTENCY_KEY_REUSE_MISMATCH = "IDEMPOTENCY_KEY_REUSE_MISMATCH"
    ARTIFACT_PERMISSION_DENIED = "ARTIFACT_PERMISSION_DENIED"
    ARTIFACT_POLICY_UNAVAILABLE = "ARTIFACT_POLICY_UNAVAILABLE"
    ARTIFACT_WORKSPACE_MISMATCH = "ARTIFACT_WORKSPACE_MISMATCH"
    ARTIFACT_QUOTA_EXCEEDED = "ARTIFACT_QUOTA_EXCEEDED"
    ARTIFACT_STORAGE_LOCKED = "ARTIFACT_STORAGE_LOCKED"
    ARTIFACT_STORAGE_CORRUPT = "ARTIFACT_STORAGE_CORRUPT"
    ARTIFACT_HASH_MISMATCH = "ARTIFACT_HASH_MISMATCH"
    ARTIFACT_ASSET_UNSAFE = "ARTIFACT_ASSET_UNSAFE"
    ARTIFACT_ASSET_TYPE_UNSUPPORTED = "ARTIFACT_ASSET_TYPE_UNSUPPORTED"
    ARTIFACT_EXPORT_CANCELLED = "ARTIFACT_EXPORT_CANCELLED"
    ARTIFACT_EXPORT_REQUIRES_CONFIRMATION = "ARTIFACT_EXPORT_REQUIRES_CONFIRMATION"
    ARTIFACT_EXPORT_FAILED = "ARTIFACT_EXPORT_FAILED"
    ARTIFACT_RPC_UNAVAILABLE = "ARTIFACT_RPC_UNAVAILABLE"
    ARTIFACT_RPC_PROTOCOL_MISMATCH = "ARTIFACT_RPC_PROTOCOL_MISMATCH"
    ARTIFACT_LICENSE_UNAVAILABLE = "ARTIFACT_LICENSE_UNAVAILABLE"
    FORM_SCHEMA_UNSAFE = "FORM_SCHEMA_UNSAFE"
    FORM_VALIDATION_FAILED = "FORM_VALIDATION_FAILED"
    FORM_SENSITIVE_PERSISTENCE_DENIED = "FORM_SENSITIVE_PERSISTENCE_DENIED"
    ASSISTANT_EVENT_SEQUENCE_GAP = "ASSISTANT_EVENT_SEQUENCE_GAP"
    ASSISTANT_ARTIFACT_PART_INVALID = "ASSISTANT_ARTIFACT_PART_INVALID"


class ArtifactDomainError(RuntimeError):
    def __init__(
        self,
        code: ArtifactErrorCode,
        message: str,
        *,
        retryable: bool = False,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.retryable = retryable
        self.details = details or {}

    def as_payload(self) -> dict[str, Any]:
        return {
            "code": self.code.value,
            "message": self.message,
            "retryable": self.retryable,
            "details": self.details,
        }
